---
engines:
  shellcheck:
    enabled: true
    # turn off client side expansion warning, as we explicitly want it
    checks:
      SC2029:
        enabled: false
      SC2016:
        enabled: false
ratings:
  paths:
  - "utils/aws-*"
exclude_paths:
  - "install.sh"
